<?php

/**
 * @file
 * The main file for the module.
 */

require_once 'splashify.display.inc';

/**
 * Implements hook_menu().
 */
function splashify_menu() {
  $items = array();

  // If they specify What: Enter Text or What: Text Full Screen, this is the
  // page that will come up.
  $items['splash'] = array(
    'title' => 'Splash',
    'page callback' => 'splashify_display_splashtext',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // Define the admin area.
  $items['admin/config/system/splashify'] = array(
    'page callback' => 'splashify_admin_main',
    'title' => 'Splashify',
    'description' => 'Access settings for displaying a splash page on your site.',
    'file' => 'splashify.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access splashify admin'),
  );

  $items['admin/config/system/splashify/info'] = array(
    'page callback' => 'splashify_admin_main',
    'title' => 'Splashify',
    'file' => 'splashify.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('access splashify admin'),
    'weight' => 4,
  );

  $items['admin/config/system/splashify/when'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('splashify_admin_when_form'),
    'title' => 'When',
    'file' => 'splashify.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access splashify admin'),
    'weight' => 6,
  );

  $items['admin/config/system/splashify/where'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('splashify_admin_where_form'),
    'title' => 'Where',
    'file' => 'splashify.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access splashify admin'),
    'weight' => 8,
  );

  $items['admin/config/system/splashify/what'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('splashify_admin_what_form'),
    'title' => 'What',
    'file' => 'splashify.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access splashify admin'),
    'weight' => 10,
  );

  $items['admin/config/system/splashify/how'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('splashify_admin_how_form'),
    'title' => 'How',
    'file' => 'splashify.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access splashify admin'),
    'weight' => 12,
  );

  return $items;
}

/**
 * Implements hook_permissions().
 */
function splashify_permissions() {
  return array(
    'access splashify admin' => array(
      'title' => t('Administer Splashify'),
      'description' => t('Access the admin area for the splashify module.'),
    ),
  );
}

/**
 * Implements hook_help().
 */
function splashify_help($path, $arg) {
  switch ($path) {
    case 'admin/help#splashify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Testing.....') . '</p>';
      return $output;
      break;

    case 'admin/config/splashify/when':
      return '<p>' . t("Define when the splash page comes up.") . '</p>';
      break;
  }
}
